// TUCCI Restaurant Employee Database
// Base de datos de empleados del restaurante TUCCI

export interface TucciEmployee {
  id: string
  firstName: string
  lastName: string
  name: string
  email: string
  phone: string
  position: string
  department: string
  hireDate: string
  status: 'active' | 'inactive' | 'terminated'
  employmentType: string
}

export const tucciEmployees: TucciEmployee[] = [
  {
    id: 'EMP001',
    firstName: 'JESUS',
    lastName: 'MORALES',
    name: 'JESUS MORALES',
    email: 'jesus.morales@tucci.com',
    phone: '(917) 851-1481',
    position: 'EXECUTIVE CHEF',
    department: 'KITCHEN',
    hireDate: '1/1/2020',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP002',
    firstName: 'KATHERINE',
    lastName: 'ALMONTI',
    name: 'KATHERINE ALMONTI',
    email: '',
    phone: '(917) 851-1481',
    position: 'CHEF',
    department: 'KITCHEN',
    hireDate: '7/16/2021',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP003',
    firstName: 'JOSE',
    lastName: 'ALTA',
    name: 'JOSE ALTA',
    email: 'altajose75@gmail.com',
    phone: '(917) 851-1481',
    hireDate: '3/1/2023',
    position: 'SOUS CHEF',
    department: 'KITCHEN',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP004',
    firstName: 'FRANKLIN',
    lastName: 'ARGUETA',
    name: 'FRANKLIN ARGUETA',
    email: '',
    phone: '(917) 851-1481',
    position: 'SOUS CHEF',
    department: 'KITCHEN',
    hireDate: '11/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP005',
    firstName: 'JOEL',
    lastName: 'BARROS',
    name: 'JOEL BARROS',
    email: 'isaattabar@hotmail.com',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '2/1/2023',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP006',
    firstName: 'GABRIEL',
    lastName: 'GUERRERO',
    name: 'GABRIEL GUERRERO',
    email: 'anguirgonzalez@hotmail.com',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '9/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP007',
    firstName: 'ALEXANDER',
    lastName: 'BREITMAN',
    name: 'ALEXANDER BREITMAN',
    email: 'albertbreitman@gmail.com',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '6/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP008',
    firstName: 'XAVIER',
    lastName: 'BRODERICK',
    name: 'XAVIER BRODERICK',
    email: 'xavierbroderick@gmail.com',
    phone: '(917) 851-1481',
    position: 'WAITER',
    department: 'FOH',
    hireDate: '5/27/2024',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP009',
    firstName: 'JUAN',
    lastName: 'CARLOS',
    name: 'JUAN CARLOS',
    email: '',
    phone: '(917) 851-1481',
    position: 'WAITER',
    department: 'FOH',
    hireDate: '6/1/2024',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP010',
    firstName: 'CARLOS',
    lastName: 'CASTELLANOS',
    name: 'CARLOS CASTELLANOS',
    email: 'castellanoscartis@icloud.com',
    phone: '(917) 851-1481',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '6/1/2028',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP011',
    firstName: 'ANGEL',
    lastName: 'CHIQUINQUIRA',
    name: 'ANGEL CHIQUINQUIRA',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '12/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP012',
    firstName: 'JOHNNY',
    lastName: 'COLON',
    name: 'JOHNNY COLON',
    email: '',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '6/13/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP013',
    firstName: 'JOANNA',
    lastName: 'DOMINICI',
    name: 'JOANNA DOMINICI',
    email: 'joannedominicci25@gmail.com',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '6/15/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP014',
    firstName: 'GABRIELA',
    lastName: 'ACOSTA',
    name: 'GABRIELA ACOSTA',
    email: '',
    phone: '(917) 851-1481',
    position: 'BAR',
    department: 'FOH',
    hireDate: '10/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP015',
    firstName: 'EDUARDO',
    lastName: 'DIAZ',
    name: 'EDUARDO DIAZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '3/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP016',
    firstName: 'ANDRES',
    lastName: 'ENRIQUE',
    name: 'ANDRES ENRIQUE',
    email: '',
    phone: '(917) 851-1481',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '12/16/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP017',
    firstName: 'FRANK',
    lastName: 'FLORES',
    name: 'FRANK FLORES',
    email: 'franky.flores.ny@gmail.com',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '6/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP018',
    firstName: 'ISAIAS',
    lastName: 'FLORES',
    name: 'ISAIAS FLORES',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '4/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP019',
    firstName: 'SAUL',
    lastName: 'GALLARDO',
    name: 'SAUL GALLARDO',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '4/15/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP020',
    firstName: 'VINCENT',
    lastName: 'GARCIA',
    name: 'VINCENT GARCIA',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '5/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP021',
    firstName: 'VICTOR',
    lastName: 'GARCIA',
    name: 'VICTOR GARCIA',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '12/27/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP022',
    firstName: 'TANIS',
    lastName: 'GODOY',
    name: 'TANIS GODOY',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '1/27/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP023',
    firstName: 'EDUARDO',
    lastName: 'GONZALEZ',
    name: 'EDUARDO GONZALEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '8/4/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP024',
    firstName: 'ALBINO',
    lastName: 'HERNANDEZ',
    name: 'ALBINO HERNANDEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '8/27/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP025',
    firstName: 'EMMANUEL',
    lastName: 'HERRERA',
    name: 'EMMANUEL HERRERA',
    email: '',
    phone: '(917) 851-1481',
    position: 'CHEF',
    department: 'FOH',
    hireDate: '1/15/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP026',
    firstName: 'JOSEPH',
    lastName: 'HICK',
    name: 'JOSEPH HICK',
    email: '',
    phone: '(917) 851-1481',
    position: 'ADMIN',
    department: 'ADMIN',
    hireDate: '4/1/2028',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP027',
    firstName: 'OLUWASEUN',
    lastName: 'IBO',
    name: 'OLUWASEUN IBO',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '10/27/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP028',
    firstName: 'JUAN',
    lastName: 'JIMENEZ',
    name: 'JUAN JIMENEZ',
    email: 'jgoncidilologo@gmail.com',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '4/1/2024',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP029',
    firstName: 'MARIAM',
    lastName: 'TSUYATIA',
    name: 'MARIAM TSUYATIA',
    email: '',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '12/16/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP030',
    firstName: 'FERNANDO',
    lastName: 'MARIN',
    name: 'FERNANDO MARIN',
    email: 'Fernandoxx88@gmail.com',
    phone: '(917) 851-1481',
    position: 'WAITER',
    department: 'FOH',
    hireDate: '3/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP031',
    firstName: 'RYKA',
    lastName: 'MAKARAIN',
    name: 'RYKA MAKARAIN',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '11/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP032',
    firstName: 'JIMMY',
    lastName: 'MERINA',
    name: 'JIMMY MERINA',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '5/27/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP033',
    firstName: 'MIGUEL',
    lastName: 'MORAN',
    name: 'MIGUEL MORAN',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '6/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP034',
    firstName: 'ANTONIO',
    lastName: 'NAYARITE',
    name: 'ANTONIO NAYARITE',
    email: '',
    phone: '(917) 851-1481',
    position: 'FOOD RUNNER',
    department: 'FOH',
    hireDate: '5/14/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP035',
    firstName: 'NICOLAS',
    lastName: 'ONEILL',
    name: 'NICOLAS ONEILL',
    email: 'nicolasoneill07@gmail.com',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '9/04/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP036',
    firstName: 'MARCO',
    lastName: 'PACHECO',
    name: 'MARCO PACHECO',
    email: '',
    phone: '(917) 851-1481',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '1/15/2025',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP037',
    firstName: 'CHRISTIAN',
    lastName: 'PEGUERO',
    name: 'CHRISTIAN PEGUERO',
    email: '',
    phone: '(917) 851-1481',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '12/1/2025',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP038',
    firstName: 'KEUVAN',
    lastName: 'PEGUERO',
    name: 'KEUVAN PEGUERO',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '3/12/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP039',
    firstName: 'ALFONSINA',
    lastName: 'PELACIOS',
    name: 'ALFONSINA PELACIOS',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '11/24/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP040',
    firstName: 'MAURICIO',
    lastName: 'PELAEZ',
    name: 'MAURICIO PELAEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '2/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP041',
    firstName: 'CAMEO',
    lastName: 'PEREZ',
    name: 'CAMEO PEREZ',
    email: 'camilop32@hotmail.com',
    phone: '(917) 851-1481',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '5/6/2024',
    status: 'active',
    employmentType: 'PART TIME'
  },
  {
    id: 'EMP042',
    firstName: 'ERICK',
    lastName: 'PEREZ',
    name: 'ERICK PEREZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '12/9/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP043',
    firstName: 'PEDRO',
    lastName: 'PEREZ',
    name: 'PEDRO PEREZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '1/15/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP044',
    firstName: 'NEPOTISM',
    lastName: 'PITLANA',
    name: 'NEPOTISM PITLANA',
    email: '',
    phone: '',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '4/24/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP045',
    firstName: 'TACNERT',
    lastName: 'RAMIREZ',
    name: 'TACNERT RAMIREZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'SERVER',
    department: 'FOH',
    hireDate: '4/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP046',
    firstName: 'GILSON',
    lastName: 'RAMIREZ',
    name: 'GILSON RAMIREZ',
    email: '',
    phone: '',
    position: 'BARTENDER',
    department: 'FOH',
    hireDate: '6/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP047',
    firstName: 'LUIS',
    lastName: 'REYNAGA',
    name: 'LUIS REYNAGA',
    email: '',
    phone: '(917) 851-1481',
    position: 'FOOD RUNNER',
    department: 'FOH',
    hireDate: '4/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP048',
    firstName: 'ERMIN',
    lastName: 'RINCHIN',
    name: 'ERMIN RINCHIN',
    email: '',
    phone: '',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '2/10/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP049',
    firstName: 'JOSE',
    lastName: 'ROSALES',
    name: 'JOSE ROSALES',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '8/13/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP050',
    firstName: 'PATRICIA',
    lastName: 'RODRIGUEZ',
    name: 'PATRICIA RODRIGUEZ',
    email: '',
    phone: '',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '8/14/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP051',
    firstName: 'MARIA',
    lastName: 'RUEDA',
    name: 'MARIA RUEDA',
    email: 'gatunomariaeduardo@gmail.com',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '8/1/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP052',
    firstName: 'LISSETH',
    lastName: 'SCOBERO',
    name: 'LISSETH SCOBERO',
    email: 'lissseth.95@gmail.com',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '11/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP053',
    firstName: 'ABBEY',
    lastName: 'SANCHEZ',
    name: 'ABBEY SANCHEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '4/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP054',
    firstName: 'NOEL',
    lastName: 'SCOBERO',
    name: 'NOEL SCOBERO',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '6/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP055',
    firstName: 'PILAR',
    lastName: 'SIGUCHA',
    name: 'PILAR SIGUCHA',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '4/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP056',
    firstName: 'DUVAN',
    lastName: 'TURQUINOVIC',
    name: 'DUVAN TURQUINOVIC',
    email: 'ivafash.timesm.com',
    phone: '(917) 851-1481',
    position: 'ADMIN',
    department: 'ADMIN',
    hireDate: '4/27/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP057',
    firstName: 'SEBASTIAN',
    lastName: 'VALLADARES',
    name: 'SEBASTIAN VALLADARES',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '12/2/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP058',
    firstName: 'MARCO',
    lastName: 'VASQUEZ',
    name: 'MARCO VASQUEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'FOOD RUNNER',
    department: 'FOH',
    hireDate: '8/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP059',
    firstName: 'JUAN',
    lastName: 'VAZQUEZ',
    name: 'JUAN VAZQUEZ',
    email: '',
    phone: '(917) 851-1481',
    position: 'BUSSER',
    department: 'FOH',
    hireDate: '11/1/2024',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP060',
    firstName: 'MARTIN',
    lastName: 'VIVALOCO',
    name: 'MARTIN VIVALOCO',
    email: '',
    phone: '(917) 851-1481',
    position: 'KITCHEN',
    department: 'BOH',
    hireDate: '2/10/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  },
  {
    id: 'EMP061',
    firstName: 'MICHELLE',
    lastName: 'WORMAC',
    name: 'MICHELLE WORMAC',
    email: '',
    phone: '(917) 851-1481',
    position: 'HOST',
    department: 'FOH',
    hireDate: '5/6/2025',
    status: 'active',
    employmentType: 'FULL TIME'
  }
]

// Convert to DirectoryEmployee format for localStorage initialization
export const getTucciEmployeesForDirectory = () => {
  return tucciEmployees.map(emp => ({
    id: emp.id,
    name: emp.name,
    email: emp.email,
    phone: emp.phone,
    position: emp.position,
    startDate: emp.hireDate,
    status: (emp.status === 'terminated' ? 'inactive' : emp.status) as 'active' | 'inactive'
  }))
}

// Also export as simplified Employee format for sales report
export const getTucciEmployeesForSales = () => {
  return tucciEmployees
    .filter(emp => emp.status === 'active')
    .map(emp => ({
      id: emp.id,
      name: emp.name,
      email: emp.email || '',
      position: emp.position
    }))
    .sort((a, b) => a.name.localeCompare(b.name))
}
